# Configuração do MoveIt Task Constructor (MTC) para o OpenArm (Braço Esquerdo)

arm_group_name: "left_arm"
hand_group_name: "left_gripper"
eef_name: "left_ee"
hand_frame: "openarm_left_link7"

hand_open_pose: "open"
hand_close_pose: "closed"

moveit_controllers:
  traj: left_joint_trajectory_controller
  gripper_traj: left_gripper_controller

joints:
  arm_joints:
    - openarm_left_joint1
    - openarm_left_joint2
    - openarm_left_joint3
    - openarm_left_joint4
    - openarm_left_joint5
    - openarm_left_joint6
    - openarm_left_joint7
  gripper_joints:
    - openarm_left_finger_joint1

poses:
  home: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  holdup: [0.0, 0.0, 0.0, 0.0, -1.57, 0.0, 0.0]