/**:
  ros__parameters:
    arm_name: "left_arm"
    hand_name: "left_gripper"
    
    # Frames de Cinemática (End-Effector / IK Frame)
    # Deve ser o link final do braço no SRDF/URDF (openarm_left_link7)
    eef_frame: "openarm_left_link7"
    world_frame: "world"
    
    # Nomes dos Joints do Gripper no SRDF
    finger_joint_name: "openarm_left_finger_joint1"
    
    # Poses do Gripper definidas no SRDF
    hand_open_pose: "open"
    hand_close_pose: "closed"
    
    # Configurações do Grasp / Aproximação MTC
    approach_distance:
      min: 0.01
      max: 0.10
    retreat_distance:
      min: 0.01
      max: 0.10
      
    # Tolerâncias e Esforço do Gripper
    max_effort: 50.0
    grasp_check:
      enabled: true
      closed_position: 0.00
      min_opening: 0.005